[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
postgres = "0.19.3"
openssl = "0.10.40"
postgres-openssl = "0.5.0"
